-- 文件上传表
CREATE TABLE upload_files (
    id bigint generated by default as identity PRIMARY KEY, -- 主键

    -- 用户标识
    user_id varchar,   -- 注册用户
    fingerprint VARCHAR(255),                                 -- 非注册用户唯一标识

    -- 批量上传标识（一个 batch 内可能包含多个文件）
    batch_id UUID NOT NULL DEFAULT gen_random_uuid(),

    -- 工具类型
    tool_type VARCHAR(50) NOT NULL,   -- e.g. 'vocal_remover', 'karaoke_maker'

    -- R2 文件信息
    original_file_name VARCHAR(255) NOT NULL,
    file_size BIGINT,
    mime_type VARCHAR(100),
    r2_key VARCHAR(500) NOT NULL,     -- 存储 path（例如：uploads/xyz.wav）

    -- 状态
    status VARCHAR(20) NOT NULL DEFAULT 'uploaded',  
    -- uploaded, processing, processed, failed

    -- 错误信息（失败时）
    error_message TEXT,

    -- 时间戳
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

