-- 非登录用户使用限制记录
CREATE TABLE anonymous_usage_limits (
    id bigint generated by default as identity PRIMARY KEY,                           -- 主键
    fingerprint VARCHAR(255) NOT NULL,                  -- 浏览器指纹（唯一标识
    tool_code VARCHAR(100) NOT NULL,                    -- 工具英文代号，如 "vocal_remover"

    initial_limit INT NOT NULL DEFAULT 0,               -- 每日初始限额（例如 3 次/天）
    used_count INT NOT NULL DEFAULT 0,                  -- 已使用次数

    last_used_at TIMESTAMP WITH TIME ZONE,              -- 最近一次使用时间
    reset_date DATE NOT NULL DEFAULT CURRENT_DATE,      -- 当天限制使用的日期用于每日重置计数

    ip_address INET,                                    -- 可选：用于风控、识别刷量
    user_agent TEXT,                                    -- 可选：识别环境 + 辅助指纹（可不存）

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    UNIQUE (fingerprint, tool_code)                     -- 每个指纹、每个工具一个限制记录
);
